export const CardData = [
  {
    id: 1,
    image: '../public/1.jpg',
    tags: [
      { tag: 'nature', id: 1 },
      { tag: 'forest', id: 2 },
    ],
    title: 'Nature is a teacher – Just sit quietly under a tree',
    person_img: '../public/tracy.png',
    person: 'Tracey Wilson',
    date: 'February 20, 2023',
  },
  {
    id: 2,
    image: '../public/2.jpg',
    tags: [
      { tag: 'nature', id: 3 },
      { tag: 'clouds', id: 4 },
    ],
    title: 'Seeing with “fresh eyes” – A deeper nature experience',
    person_img: '../public/jason.png',
    person: 'Jason Francisco',
    date: 'February 18, 2023',
  },
  {
    id: 3,
    image: '../public/3.jpg',
    tags: [{ tag: 'urban', id: 5 }],
    title: 'A Quick Thought on The Nature of Travel',
    person_img: '../public/lizzy.png',
    person: 'Elizabeth Slavin',
    date: 'February 18, 2023',
  },
  {
    id: 4,
    image: '../public/4.jpg',
    tags: [{ tag: 'urban', id: 6 }],
    title: 'Best Things to do in Madrid, Spain',
    person_img: '../public/ernie.png',
    person: 'Ernie Smithn',
    date: 'February 17, 2023',
  },
  {
    id: 5,
    image: '../public/5.jpg',
    tags: [
      { tag: 'nature', id: 7 },
      { tag: 'desert', id: 8 },
    ],
    title: 'Sahara Morocco: Visit the Merzouga Desert in a 3-Day Tour',
    person_img: '../public/eric.png',
    person: 'Eric Smith',
    date: 'February 14, 2023',
  },
  {
    id: 6,
    image: '../public/6.jpg',
    tags: [{ tag: 'nature', id: 9 }],
    title: 'Earth’s intelligence: Being pulled toward the heart of the world',
    person_img: '../public/tracy.png',
    person: 'Tracey Wilson',
    date: 'February 14, 2023',
  },
  {
    id: 7,
    image: '../public/7.jpg',
    tags: [
      { tag: 'nature', id: 10 },
      { tag: 'sea', id: 11 },
    ],
    title: 'The hug of homecoming: Hedonism in the natural world',
    person_img: '../public/jason.png',
    person: 'Jason Francisco',
    date: 'February 13, 2023',
  },
  {
    id: 8,
    image: '../public/8.png',
    tags: [
      { tag: 'nature', id: 12 },
      { tag: 'sea', id: 13 },
    ],
    title: 'Nature Connection Exercise – Perceive and Receive',
    person_img: '../public/lizzy.png',
    person: 'Elizabeth Slavin',
    date: 'February 10, 2023',
  },
  {
    id: 9,
    image: '../public/9.jpg',
    tags: [{ tag: 'urban', id: 14 }],
    title: 'Golden Gate Bridge – History, Construction, & Facts',
    person_img: '../public/ernie.png',
    person: 'Ernie Smith',
    date: 'February 9, 2023',
  },
];
