export const CardData = [
  {
    id: 1,
    image: '../public/1.jpg',
    title: 'Nature is a teacher – Just sit quietly under a tree',
    personImg: '../public/tracy.png',
    person: 'Tracey Wilson',
    date: 'February 20, 2023',
  },
  {
    id: 2,
    image: '../public/2.jpg',
    title: 'Seeing with “fresh eyes” – A deeper nature experience',
    personImg: '../public/jason.png',
    person: 'Jason Francisco',
    date: 'February 18, 2023',
  },
  {
    id: 3,
    image: '../public/3.jpg',
    title: 'A Quick Thought on The Nature of Travel',
    personImg: '../public/lizzy.png',
    person: 'Elizabeth Slavin',
    date: 'February 18, 2023',
  },
  {
    id: 4,
    image: '../public/4.jpg',
    title: 'Best Things to do in Madrid, Spain',
    personImg: '../public/ernie.png',
    person: 'Ernie Smithn',
    date: 'February 17, 2023',
  },
  {
    id: 5,
    image: '../public/5.jpg',
    title: 'Sahara Morocco: Visit the Merzouga Desert in a 3-Day Tour',
    personImg: '../public/eric.png',
    person: 'Eric Smith',
    date: 'February 14, 2023',
  },
  {
    id: 6,
    image: '../public/6.jpg',
    title: 'Earth’s intelligence: Being pulled toward the heart of the world',
    personImg: '../public/tracy.png',
    person: 'Tracey Wilson',
    date: 'February 14, 2023',
  },
  {
    id: 7,
    image: '../public/7.jpg',
    title: 'The hug of homecoming: Hedonism in the natural world',
    personImg: '../public/jason.png',
    person: 'Jason Francisco',
    date: 'February 13, 2023',
  },
  {
    id: 8,
    image: '../public/8.png',
    title: 'Nature Connection Exercise – Perceive and Receive',
    personImg: '../public/lizzy.png',
    person: 'Elizabeth Slavin',
    date: 'February 10, 2023',
  },
  {
    id: 9,
    image: '../public/9.jpg',
    title: 'Golden Gate Bridge – History, Construction, & Facts',
    personImg: '../public/ernie.png',
    person: 'Ernie Smith',
    date: 'February 9, 2023',
  },
];
